"""财务ERP系统 database schema description for NL2SQL."""

ALLOWED_TABLES = [
    "tenants",
    "employees",
    "customers",
    "customer_contacts",
    "tasks",
    "task_flow_logs",
    "payments",
    "fuel_records",
    "weighing_records",
    "attendance_records",
    "shift_records",
    "expense_records",
    "inventory_records",
    "material_prices",
    "job_salaries",
    "files",
]

SCHEMA_DESCRIPTION = {
    "tenants": {
        "description": "租户/公司",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "name", "type": "VARCHAR(200)", "description": "公司名称"},
            {"name": "slug", "type": "VARCHAR(50)", "description": "URL标识"},
            {"name": "is_active", "type": "BOOLEAN", "description": "是否启用"},
            {"name": "contact_person", "type": "VARCHAR(50)", "description": "联系人"},
            {"name": "contact_phone", "type": "VARCHAR(20)", "description": "联系电话"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "employees": {
        "description": "员工",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "username", "type": "VARCHAR(50)", "description": "用户名"},
            {"name": "real_name", "type": "VARCHAR(50)", "description": "真实姓名"},
            {"name": "phone", "type": "VARCHAR(20)", "description": "电话"},
            {"name": "email", "type": "VARCHAR(100)", "description": "邮箱"},
            {"name": "is_active", "type": "BOOLEAN", "description": "是否在职"},
            {"name": "role", "type": "VARCHAR(20)", "description": "角色: admin/operator/driver/ext_driver"},
            {"name": "job_type", "type": "VARCHAR(50)", "description": "工种"},
            {"name": "module_access", "type": "JSON", "description": "模块权限"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "customers": {
        "description": "客户",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "company_name", "type": "VARCHAR(200)", "description": "公司名称"},
            {"name": "unified_social_credit_code", "type": "VARCHAR(50)", "description": "统一社会信用代码"},
            {"name": "legal_representative", "type": "VARCHAR(50)", "description": "法定代表人"},
            {"name": "registered_address", "type": "TEXT", "description": "注册地址"},
            {"name": "business_scope", "type": "TEXT", "description": "经营范围"},
            {"name": "contact_person", "type": "VARCHAR(50)", "description": "联系人"},
            {"name": "contact_phone", "type": "VARCHAR(20)", "description": "联系电话"},
            {"name": "contact_email", "type": "VARCHAR(100)", "description": "联系邮箱"},
            {"name": "service_start_date", "type": "DATE", "description": "服务开始日期"},
            {"name": "service_status", "type": "VARCHAR(20)", "description": "服务状态: active/suspended/terminated"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_by", "type": "UUID FK→employees", "description": "创建人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "customer_contacts": {
        "description": "客户联系人",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "contact_name", "type": "VARCHAR(50)", "description": "联系人姓名"},
            {"name": "position", "type": "VARCHAR(50)", "description": "职位"},
            {"name": "phone", "type": "VARCHAR(20)", "description": "电话"},
            {"name": "email", "type": "VARCHAR(100)", "description": "邮箱"},
            {"name": "is_primary", "type": "BOOLEAN", "description": "是否主要联系人"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "tasks": {
        "description": "工单",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "task_number", "type": "VARCHAR(50)", "description": "工单编号"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "task_type", "type": "VARCHAR(50)", "description": "工单类型: company_registration/tax_declaration等"},
            {"name": "title", "type": "VARCHAR(200)", "description": "标题"},
            {"name": "description", "type": "TEXT", "description": "描述"},
            {"name": "status", "type": "VARCHAR(50)", "description": "状态: created/assigned_to_business等"},
            {"name": "priority", "type": "VARCHAR(20)", "description": "优先级: low/normal/high/urgent"},
            {"name": "current_assignee_id", "type": "UUID FK→employees", "description": "当前处理人"},
            {"name": "estimated_completion_date", "type": "DATE", "description": "预计完成日期"},
            {"name": "actual_completion_date", "type": "TIMESTAMP", "description": "实际完成日期"},
            {"name": "business_requirements", "type": "TEXT", "description": "业务需求"},
            {"name": "service_amount", "type": "DECIMAL(15,2)", "description": "服务费用"},
            {"name": "created_by", "type": "UUID FK→employees", "description": "创建人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "task_flow_logs": {
        "description": "工单流转记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "task_id", "type": "UUID FK→tasks", "description": "关联工单"},
            {"name": "from_status", "type": "VARCHAR(50)", "description": "原状态"},
            {"name": "to_status", "type": "VARCHAR(50)", "description": "目标状态"},
            {"name": "from_assignee_id", "type": "UUID FK→employees", "description": "原处理人"},
            {"name": "to_assignee_id", "type": "UUID FK→employees", "description": "目标处理人"},
            {"name": "operator_id", "type": "UUID FK→employees", "description": "操作人"},
            {"name": "operation_type", "type": "VARCHAR(50)", "description": "操作类型: create/assign/start_process/complete等"},
            {"name": "content", "type": "TEXT", "description": "操作内容"},
            {"name": "duration_seconds", "type": "INTEGER", "description": "处理时长(秒)"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "payments": {
        "description": "费用/收款记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "payment_number", "type": "VARCHAR(50)", "description": "收款单号"},
            {"name": "task_id", "type": "UUID FK→tasks", "description": "关联工单"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "payment_type", "type": "VARCHAR(50)", "description": "费用类型: service_fee/registration_fee等"},
            {"name": "amount_due", "type": "DECIMAL(15,2)", "description": "应收金额"},
            {"name": "amount_paid", "type": "DECIMAL(15,2)", "description": "已收金额"},
            {"name": "payment_status", "type": "VARCHAR(50)", "description": "收款状态: unpaid/partial/paid/overdue"},
            {"name": "payment_method", "type": "VARCHAR(50)", "description": "付款方式: cash/bank_transfer/alipay/wechat"},
            {"name": "payment_date", "type": "DATE", "description": "收款日期"},
            {"name": "invoice_issued", "type": "BOOLEAN", "description": "是否已开发票"},
            {"name": "invoice_number", "type": "VARCHAR(50)", "description": "发票号"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_by", "type": "UUID FK→employees", "description": "创建人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "fuel_records": {
        "description": "加油/充电记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "record_type", "type": "ENUM(fuel,charging)", "description": "记录类型：加油/充电"},
            {"name": "vehicle_category", "type": "ENUM(upper_shovel,lower_shovel,tricycle,sprinkler,truck,kiln,yutong_ev)", "description": "车辆类型：上铲/下铲/三轮车/洒水车/大车/窑口/宇通电车"},
            {"name": "date", "type": "DATE", "description": "记录日期"},
            {"name": "quantity", "type": "DECIMAL(10,2)", "description": "数量（升或度）"},
            {"name": "operator_id", "type": "UUID FK→employees", "description": "操作人"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "weighing_records": {
        "description": "司磅/过磅记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "record_type", "type": "ENUM(inbound,outbound)", "description": "记录类型：进货(RK)/出货(CK)"},
            {"name": "slip_number", "type": "VARCHAR(50)", "description": "磅单号"},
            {"name": "vehicle_number", "type": "VARCHAR(50)", "description": "车号"},
            {"name": "driver_phone", "type": "VARCHAR(20)", "description": "司机电话"},
            {"name": "material_name", "type": "VARCHAR(100)", "description": "品名/物料名称"},
            {"name": "receiver", "type": "VARCHAR(200)", "description": "收货单位"},
            {"name": "supplier", "type": "VARCHAR(200)", "description": "供货单位"},
            {"name": "gross_weight", "type": "DECIMAL(10,2)", "description": "毛重(吨)"},
            {"name": "tare_weight", "type": "DECIMAL(10,2)", "description": "皮重(吨)"},
            {"name": "net_weight", "type": "DECIMAL(10,2)", "description": "净重(吨)"},
            {"name": "unit_price", "type": "DECIMAL(10,2)", "description": "单价(元/吨)"},
            {"name": "total_amount", "type": "DECIMAL(15,2)", "description": "总金额(元)"},
            {"name": "gross_weight_time", "type": "TIMESTAMP", "description": "毛重时间(上磅)"},
            {"name": "tare_weight_time", "type": "TIMESTAMP", "description": "皮重时间(下磅)"},
            {"name": "original_count", "type": "VARCHAR(50)", "description": "原发数(仅进货)"},
            {"name": "receiver_quantity", "type": "DECIMAL(10,2)", "description": "对方收货数量(吨，仅出货)"},
            {"name": "product_model", "type": "VARCHAR(100)", "description": "型号规格"},
            {"name": "data_source", "type": "VARCHAR(20)", "description": "数据来源: manual/webhook"},
            {"name": "uploaded_by", "type": "UUID FK→employees", "description": "上传人"},
            {"name": "uploaded_at", "type": "TIMESTAMP", "description": "上传时间"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "attendance_records": {
        "description": "考勤打卡记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "employee_id", "type": "UUID FK→employees", "description": "关联员工"},
            {"name": "check_type", "type": "ENUM(clock_in,clock_out)", "description": "打卡类型：上班/下班"},
            {"name": "check_date", "type": "DATE", "description": "打卡日期"},
            {"name": "check_time", "type": "TIMESTAMP", "description": "打卡时间"},
            {"name": "latitude", "type": "DECIMAL(10,7)", "description": "纬度"},
            {"name": "longitude", "type": "DECIMAL(10,7)", "description": "经度"},
            {"name": "distance", "type": "DECIMAL(10,2)", "description": "距打卡点距离(米)"},
            {"name": "is_in_range", "type": "VARCHAR(10)", "description": "是否在范围内"},
            {"name": "notes", "type": "VARCHAR(200)", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "shift_records": {
        "description": "班次/排班记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "employee_id", "type": "UUID FK→employees", "description": "关联员工"},
            {"name": "date", "type": "DATE", "description": "日期"},
            {"name": "job_type", "type": "VARCHAR(50)", "description": "岗位/工种"},
            {"name": "shift_type", "type": "VARCHAR(20)", "description": "班次类型: normal/overtime/leave/dayoff"},
            {"name": "start_time", "type": "TIMESTAMP", "description": "开始时间"},
            {"name": "end_time", "type": "TIMESTAMP", "description": "结束时间"},
            {"name": "hours", "type": "DECIMAL(5,1)", "description": "工时(小时)"},
            {"name": "quantity", "type": "DECIMAL(10,2)", "description": "计件数量（吨/车）"},
            {"name": "salary", "type": "DECIMAL(10,2)", "description": "该班次薪资(元)"},
            {"name": "status", "type": "VARCHAR(20)", "description": "状态: normal/abnormal"},
            {"name": "source", "type": "VARCHAR(20)", "description": "来源: attendance_auto/manual"},
            {"name": "notes", "type": "VARCHAR(500)", "description": "备注"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "expense_records": {
        "description": "额外开支记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "employee_id", "type": "UUID FK→employees", "description": "关联员工"},
            {"name": "date", "type": "DATE", "description": "日期"},
            {"name": "category", "type": "VARCHAR(50)", "description": "开支类别: 外部电费/过路费/装卸车费/信息费/其它/罚款付现"},
            {"name": "amount", "type": "DECIMAL(10,2)", "description": "金额(元)"},
            {"name": "notes", "type": "TEXT", "description": "备注说明"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "inventory_records": {
        "description": "库存入库记录",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "date", "type": "DATE", "description": "日期"},
            {"name": "material_name", "type": "VARCHAR(100)", "description": "物料名称"},
            {"name": "quantity", "type": "DECIMAL(12,2)", "description": "数量"},
            {"name": "unit", "type": "VARCHAR(20)", "description": "单位"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
            {"name": "operator_id", "type": "UUID FK→employees", "description": "操作人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "material_prices": {
        "description": "物料单价配置",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "company_name", "type": "VARCHAR(200)", "description": "公司名称"},
            {"name": "material_name", "type": "VARCHAR(100)", "description": "物料名称"},
            {"name": "unit_price", "type": "DECIMAL(10,2)", "description": "单价"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "job_salaries": {
        "description": "工种工资配置",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "job_type", "type": "VARCHAR(50)", "description": "工种"},
            {"name": "base_salary", "type": "DECIMAL(10,2)", "description": "基本工资"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "updated_at", "type": "TIMESTAMP", "description": "更新时间"},
        ],
    },
    "files": {
        "description": "文件附件",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "tenant_id", "type": "UUID FK→tenants", "description": "关联租户"},
            {"name": "original_name", "type": "VARCHAR(255)", "description": "原始文件名"},
            {"name": "file_size", "type": "BIGINT", "description": "文件大小(字节)"},
            {"name": "file_type", "type": "VARCHAR(100)", "description": "MIME类型"},
            {"name": "category", "type": "VARCHAR(50)", "description": "文件分类"},
            {"name": "relation_type", "type": "VARCHAR(50)", "description": "关联类型: customer/task"},
            {"name": "relation_id", "type": "UUID", "description": "关联ID"},
            {"name": "uploaded_by", "type": "UUID FK→employees", "description": "上传人"},
            {"name": "uploaded_at", "type": "TIMESTAMP", "description": "上传时间"},
            {"name": "is_deleted", "type": "BOOLEAN", "description": "是否已删除"},
        ],
    },
}
