"""XingERP database schema description for NL2SQL."""

ALLOWED_TABLES = [
    "customers", "customer_contacts", "customer_fees", "fee_templates",
    "tasks", "task_flow_logs", "task_templates",
    "employees",
    "service_types", "service_packages", "service_package_items",
    "customer_service_relations",
    "workflow_instances", "workflow_stage_instances", "workflow_stage_logs",
    "comments", "notifications", "files", "payments",
]

SCHEMA_DESCRIPTION = {
    "customers": {
        "description": "客户表（公司）",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "company_name", "type": "VARCHAR(200)", "description": "公司名称"},
            {"name": "customer_code", "type": "VARCHAR(50)", "description": "客户编号（如 2-001）"},
            {"name": "unified_social_credit_code", "type": "VARCHAR(50)", "description": "统一社会信用代码"},
            {"name": "legal_representative", "type": "VARCHAR(50)", "description": "法定代表人"},
            {"name": "contact_person", "type": "VARCHAR(50)", "description": "联系人"},
            {"name": "contact_phone", "type": "VARCHAR(20)", "description": "联系电话"},
            {"name": "service_status", "type": "VARCHAR(20)", "description": "服务状态: active/suspended/terminated"},
            {"name": "service_start_date", "type": "DATE", "description": "服务开始日期"},
            {"name": "assigned_accountant_id", "type": "UUID FK→employees", "description": "分属会计"},
            {"name": "assigned_business_staff_id", "type": "UUID FK→employees", "description": "分属工商员"},
            {"name": "assigned_collection_staff_id", "type": "UUID FK→employees", "description": "分属催缴专员"},
            {"name": "is_deleted", "type": "BOOLEAN", "description": "是否已删除（查询时请加 is_deleted=false）"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "notes", "type": "TEXT", "description": "备注"},
        ],
    },
    "employees": {
        "description": "员工表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "username", "type": "VARCHAR(50)", "description": "英文登录名"},
            {"name": "account_name", "type": "VARCHAR(50)", "description": "中文账号名（对外显示）"},
            {"name": "real_name", "type": "VARCHAR(50)", "description": "真实姓名"},
            {"name": "phone", "type": "VARCHAR(20)", "description": "电话"},
            {"name": "email", "type": "VARCHAR(100)", "description": "邮箱"},
            {"name": "employee_code", "type": "VARCHAR(20)", "description": "员工编号（如 ACC-100）"},
            {"name": "is_active", "type": "BOOLEAN", "description": "是否在职"},
            {"name": "is_accountant", "type": "BOOLEAN", "description": "是否是会计"},
            {"name": "accountant_group", "type": "VARCHAR(50)", "description": "会计分组"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "tasks": {
        "description": "工单表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "task_number", "type": "VARCHAR(50)", "description": "工单编号（唯一）"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "task_type", "type": "VARCHAR(50)", "description": "工单类型: company_registration, tax_declaration 等"},
            {"name": "title", "type": "VARCHAR(200)", "description": "工单标题"},
            {"name": "status", "type": "VARCHAR(50)", "description": "状态: created, assigned_to_business, in_progress, completed, cancelled 等"},
            {"name": "priority", "type": "VARCHAR(20)", "description": "优先级: low/normal/high/urgent"},
            {"name": "current_assignee_id", "type": "UUID FK→employees", "description": "当前负责人"},
            {"name": "service_amount", "type": "DECIMAL(15,2)", "description": "服务费用"},
            {"name": "created_by", "type": "UUID FK→employees", "description": "创建人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
            {"name": "estimated_completion_date", "type": "DATE", "description": "预计完成日期"},
            {"name": "actual_completion_date", "type": "TIMESTAMP", "description": "实际完成时间"},
            {"name": "is_workflow_task", "type": "BOOLEAN", "description": "是否为工作流工单"},
            {"name": "workflow_stage", "type": "INTEGER", "description": "工作流阶段 1-6"},
        ],
    },
    "task_flow_logs": {
        "description": "工单状态流转日志",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "task_id", "type": "UUID FK→tasks", "description": "关联工单"},
            {"name": "from_status", "type": "VARCHAR(50)", "description": "原状态"},
            {"name": "to_status", "type": "VARCHAR(50)", "description": "新状态"},
            {"name": "operation_type", "type": "VARCHAR(50)", "description": "操作类型"},
            {"name": "content", "type": "TEXT", "description": "操作内容/备注"},
            {"name": "operator_id", "type": "UUID FK→employees", "description": "操作人"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "操作时间"},
        ],
    },
    "customer_fees": {
        "description": "客户费用表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "fee_name", "type": "VARCHAR(100)", "description": "费用名称"},
            {"name": "fee_amount", "type": "DECIMAL(10,2)", "description": "费用金额"},
            {"name": "billing_cycle", "type": "VARCHAR(20)", "description": "计费周期: monthly/yearly/one_time"},
            {"name": "payment_status", "type": "VARCHAR(20)", "description": "付款状态: unpaid/paid"},
            {"name": "is_active", "type": "BOOLEAN", "description": "是否有效"},
            {"name": "paid_at", "type": "TIMESTAMP", "description": "支付时间"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "service_types": {
        "description": "服务类型表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "type_code", "type": "VARCHAR(20)", "description": "服务代码（如 ACCOUNTING）"},
            {"name": "type_name", "type": "VARCHAR(100)", "description": "服务名称（如 记账费）"},
            {"name": "service_category", "type": "VARCHAR(20)", "description": "业务分类: recurring/on_demand/one_time"},
            {"name": "default_fee_amount", "type": "DECIMAL(10,2)", "description": "默认费用"},
            {"name": "is_active", "type": "BOOLEAN", "description": "是否有效"},
            {"name": "use_workflow", "type": "BOOLEAN", "description": "是否启用工作流"},
        ],
    },
    "workflow_instances": {
        "description": "工作流实例",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "service_type_id", "type": "UUID FK→service_types", "description": "关联服务类型"},
            {"name": "status", "type": "VARCHAR(20)", "description": "状态: not_started/in_progress/completed/cancelled"},
            {"name": "started_at", "type": "TIMESTAMP", "description": "开始时间"},
            {"name": "completed_at", "type": "TIMESTAMP", "description": "完成时间"},
        ],
    },
    "workflow_stage_instances": {
        "description": "工作流阶段实例",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "workflow_instance_id", "type": "UUID FK→workflow_instances", "description": "关联工作流"},
            {"name": "stage_name", "type": "VARCHAR(100)", "description": "阶段名称"},
            {"name": "stage_order", "type": "INTEGER", "description": "顺序"},
            {"name": "assigned_employee_id", "type": "UUID FK→employees", "description": "负责人"},
            {"name": "status", "type": "VARCHAR(20)", "description": "状态: pending/in_progress/completed/skipped"},
            {"name": "stage_type", "type": "VARCHAR(20)", "description": "类型: one_time/recurring"},
        ],
    },
    "payments": {
        "description": "收款记录表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "payment_number", "type": "VARCHAR(50)", "description": "收款单号"},
            {"name": "customer_id", "type": "UUID FK→customers", "description": "关联客户"},
            {"name": "amount_due", "type": "DECIMAL(15,2)", "description": "应收金额"},
            {"name": "amount_paid", "type": "DECIMAL(15,2)", "description": "已收金额"},
            {"name": "payment_status", "type": "VARCHAR(50)", "description": "状态: unpaid/partial/paid/overdue"},
            {"name": "payment_method", "type": "VARCHAR(50)", "description": "支付方式: cash/bank_transfer/alipay/wechat"},
            {"name": "payment_date", "type": "DATE", "description": "收款日期"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
    "comments": {
        "description": "评论/备注表",
        "columns": [
            {"name": "id", "type": "UUID", "description": "主键"},
            {"name": "content", "type": "TEXT", "description": "评论内容"},
            {"name": "created_at", "type": "TIMESTAMP", "description": "创建时间"},
        ],
    },
}
